baseURL = "https://hermanka.github.io/"
languageCode = "en-us"
theme = "tale"
title = "HermanKabetta"
summaryLength = 70
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy;HK 2019"

[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
description = "Herman Kabetta's personal page"
twitter = "your_twitter_id"
# You can use favicon by addin them manually.
useIcon = true
useTwitterCard = false
author = "Herman Kabetta"

shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
showFooterCredits = false

[menu]

  [[menu.main]]
    identifire = "publications"
    name = "Publications"
    url = "/pubs"
    weight = -100

  [[menu.main]]
    identifire = "archives"
    name = "Archives"
    url = "/archives/"
    weight = -110

  [[menu.main]]
    identifire = "home"
    name = "Home"
    url = "/"
    weight = -120

